### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by Fshamri** [ktsl/retrovolley#10]
how to pass username and password

**Comment by serj-lotutovici** [comment]
All depends on your API.

If you need to pass them as GET or POST params just use the builder method `addParam(String, String)`:

```
new RequestBuilder<YourReturnType>(YourRequestEnum.LOGIN)
        .addParam("your_login_key", "user_login")
        .addParam("your_password_key", "user_password")
        // Add other stuff you need (headers, listeners, etc)
        .execute();
```

If your server expects json or any other format data, you can add it with `setBody(String)` or `setBody(Object)` (in this case RetroVolley will try to serialise your object in your format, by default its JSON).
